version: '3.8'

services:
  # Production pipeline service
  product-pipeline:
    build:
      context: .
      target: production
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - INSIDE_DOCKER=1
    user: "1000:1000"
    command: ["python", "-m", "product_pipeline.main", "--repo_name", "ProductA"]

  # Development environment
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - INSIDE_DOCKER=1
    user: "1000:1000"
    command: ["python", "-m", "product_pipeline.main", "--help"]

  # Test environment
  test:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - INSIDE_DOCKER=1
    user: "1000:1000"
    command: ["python", "-m", "pytest", "tests/", "-v"]

  # Code quality checks
  quality:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - INSIDE_DOCKER=1
    user: "1000:1000"
    command: ["python", "-m", "pytest", "tests/", "--cov=src", "--cov-report=term"] 